### ISSUE TITLE
RADIUS/TLS with non-encrypting TLS cipher suites

### ISSUE THREAD

**Issue by alandekok** [Janfred/draft-janfred-radext-radiusdtls-bis#3]
IEC 62351-3:2023 allows for non-encrypting cipher suites.

  It has some text which somewhat addresses the security issues:

> Any cipher suite that specifies NULL for encryption shall not be used for communication outside the administrative domain if the encryption of this communication connection by other means cannot be guaranteed.

  But that doesn't really help.  Given that RFC 6614 suggests the use of a fixed shared secret "radsec", this means that anyone in your local domain can see and decode the User-Password.

  Furthermore text says:

> The application of no-encrypting cipher suites allows for traffic inspection, while still retaining an end-to- end authentication and integrity protection of the traffic.

  They also allow the following cipher suites for TLS 1.3:

> –  TLS_SHA256_SHA256 (RFC 9150)
>  –  TLS_SHA384_SHA384 (RFC 9150)

  If there is a need to monitor traffic, just use RADIUS/UDP.  RADIUS/TLS with NULL encryption is worse than UDP in every possible way.  It has all of the worst aspects of UDP (everything in the clear) plus all of the worst aspect of TCP (head of line blocking) plus the ability for anyone to see all of your passwords!

  The document contains no warnings that the use of "radsec" as a shared secret will result in compromised passwords.

  Either the IEC specification or implementations should do one of the following:

1) forbid non-encrypting cipher suites for TLS 1.2 and TLS 1.3

 or

2) forbid the use of the "radsec" shared secret for TLS 1.2 and TLS 1.3.  Require that the shared secret is at least 16 characters long.  Ideally generated a random shared secret, and suggest it to the admin.

 Without these precautions, User-Passwords will be sent across the network, effectively in clear-text.

**Comment by restena-sw** [comment]
RFC6614 already forbids those ever since:

"Negotiation of a ciphersuite providing for confidentiality as
          well as integrity protection is REQUIRED.  Failure to comply
          with this requirement can lead to severe security problems,
          like user passwords being recoverable by third parties.  See
          [Section 6](https://www.rfc-editor.org/rfc/rfc6614#section-6) for details."

If the IEC suggests otherwise, IMHO this other spec should be fixed.

**Comment by alandekok** [comment]
@restena-sw I agree.  I had a deeper look at 6614, and found that text.

I've also talked with the IEC people, and they're now aware of these issues.  The hope is to get them to update their specification.

In the mean time, I believe it's useful to address these issues in a little more detail in 6614bis.  e.g. "While it may seem useful to allow NULL encryption for deep packet inspection, such use-cases result in significantly decreased security" etc.

**Comment by Janfred** [comment]
The question is if this document is the right place for this. 
The current draft text explicitly references RFC9325. And RFC9325 states (section 4.1):
> Implementations MUST NOT negotiate the cipher suites with NULL encryption.
> Rationale: The NULL cipher suites do not encrypt traffic and so provide no confidentiality services. Any entity in the network with access to the connection can view the plaintext of contents being exchanged by the client and server. Nevertheless, this document does not discourage software from implementing NULL cipher suites, since they can be useful for testing and debugging.

I think this is clear enough. If people want to shoot themselves in the foot, we have no way of preventing that, but explicitly stating "beware of eNULL ciphers, things may break then" maybe is the thing that gives people the idea to do this stupid thing.

(Not generally opposed to add a sentence in the security considerations section about it though, just wanted to add another point of view)

**Comment by alandekok** [comment]
@Janfred I'm a big fan of adding text which names bad behavior and explains why it's bad.

There is a strong tendency for some people to say "It isn't forbidden by the RFCs, therefore it's allowed".  Or in this case "It's forbidden, but we still find it useful for reasons A, B, and C".   If we name those reasons and explain why they're wrong, it can cut down on bad things.  If it's just a sentence or two, then it's not much work.
